Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Lecturer Communications and Journalism - UNSW" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Lecturer"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Lecturer Teaching and Research - Cardiff" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Lecturer"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\EKC" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Lecturer"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\British Academy Postdoctoral Fellowship - Warwick" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Postdoctoral"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Post-Doctoral Research Fellow Journalism and Democracy - City" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Postdoctoral"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Research Fellowships AI for Life - Liverpool" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Research Fellow"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Communications Intern - RSB" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Intern"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\UK Global Talent Visa Academic Route" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Visa"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Call for Concept Notes - Tetfund" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Grant"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\ECREA-Pre-Conference Workshop" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Workshop"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\absw" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Other"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\AcadCV" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Other"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Careers Coach - CCCU" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Other"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\CivilServiceJobs" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Other"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\FHEA" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Other"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Health and Social Care Worker - HCA" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Other"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\NetworkRail" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Other"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\others" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Other"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\psychologyCogent" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Other"
Move-Item -Path "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\UoManchester" -Destination "c:\Users\user\OneDrive\Documents\CV\MyCVs\acad\opportunities\Other"